module.exports = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
	MESSAGE_SENT:"MESSAGE_SENT",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	TYPING:"TYPING",
	VERIFY_USER:"VERIFY_USER",
	LOGIN_WITH_DEVICEID:"LOGIN_WITH_DEVICEID",
	GET_CHARACTERS:"GET_CHARACTERS",
	SET_CHARACTER:"SET_CHARACTER",
	LOGOUT:"LOGOUT",

	SERVER_UPDATE:"SERVER_UPDATE",
	GAME_UPDATE:"GAME_UPDATE",
	PLAYER_INPUT:"PLAYER_INPUT",
	CREATE_GAME:"CREATE_GAME",
	START_GAME:"START_GAME",
	JOIN_GAME:"JOIN_GAME",
	LEAVE_GAME:"LEAVE_GAME",
	GAME_OVER:"GAME_OVER",
	ACTIVE_GAME:"ACTIVE_GAME",
	CLIENT_ADDED:"CLIENT_ADDED",
	UPDATE_LIST:"UPDATE_LIST",
	WINNER:"WINNER",
	LOSER:"LOSER",
	LEAVE:"LEAVE"
}

